Api/config/routes.rb
Rails.application.routes.draw do
  root to: 'staticpage#index'
  get '/about', to: 'staticpage#about'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Api/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

Api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Api/app/models/event.rb
class Event < ApplicationRecord
end

Api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Api/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  PER = 10
  # GET /events
  # GET /events.json
  def index
    @events = Event.page(params[:page]).per(PER)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :catch, :img_url, :event_url, :event_id, :started_at, :ended_at, :address)
    end
end

Api/app/controllers/staticpage_controller.rb
class StaticpageController < ApplicationController
  def index
  end

  def about
  end

  def help
  end
end

Api/app/helpers/application_helper.rb
module ApplicationHelper
end

Api/app/helpers/events_helper.rb
module EventsHelper
end

Api/app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :catch %>
    <%= form.text_field :catch %>
  </div>

  <div class="field">
    <%= form.label :img_url %>
    <%= form.text_field :img_url %>
  </div>

  <div class="field">
    <%= form.label :event_url %>
    <%= form.text_field :event_url %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.number_field :event_id %>
  </div>

  <div class="field">
    <%= form.label :started_at %>
    <%= form.datetime_select :started_at %>
  </div>

  <div class="field">
    <%= form.label :ended_at %>
    <%= form.datetime_select :ended_at %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Api/app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

Api/app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>
  <%= paginate @events %>
  <ul class="collection">
    <% @events.each_with_index do |event, i| %>
    <% if i % 2 == 0 %>
      <div class="row">
    <% end %>
    <div class="col s6">
      <div class="card large">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag event.img_url, :class => "activator" %>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= event.title %><i class="material-icons right">more_vert</i></span>
          <p>
            <i class="medium material-icons" onClick="window.open('<%=event.event_url%>')">web</i>
            <%= link_to event do%>
            <i class="medium material-icons">fullscreene</i>
            <%end %>
          </p>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"><%= event.title %><i class="material-icons right">close</i></span>
          <ul class="collection">
            <li class="collection-item avatar">
              <i class="material-icons circle purple accent-4">subtitles</i>
              <span class="title">概要</span>
              <p><%= event.catch %><br>
              </p>
            </li>
            <li class="collection-item avatar">
              <i class="material-icons circle purple accent-4">web</i>
              <span class="title">イベントページ</span>
              <p><%= link_to event.event_url, event.event_url %><br>
              </p>
            </li>
            <li class="collection-item avatar">
              <i class="material-icons circle purple accent-4">search</i>
              <span class="title">イベントid</span>
              <p><%= event.event_id %><br>
              </p>
            </li>
            <li class="collection-item avatar">
              <i class="material-icons circle purple accent-4">date_range</i>
              <span class="title">時間</span>
              <p><%= event.started_at %> ~ <%= event.ended_at %><br>
              </p>
            </li>
            <li class="collection-item avatar">
             <i class="material-icons circle purple accent-4">place</i>
             <span class="title">場所</span>
             <p><%= event.address %><br>
             </p>
           </li>
         </ul>
        </div>
      </div>
    </div>
    <% if i % 2 != 0 %>
      </div>
    <% end %>
    <% end %>
</ul>
<%= paginate @events %>

Api/app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

Api/app/views/events/show.html.erb
<div class="container">
  <div class="row">
      <div class="col s6">
        <ul class="collection with-header">
          <li class="collection-header"><h5><%= @event.title %></h5></li>
          <li class="collection-item avatar">
            <i class="material-icons circle purple accent-4">subtitles</i>
            <span class="title">概要</span>
            <p><%= @event.catch %><br>
            </p>
          </li>
          <li class="collection-item avatar">
            <i class="material-icons circle purple accent-4">web</i>
            <span class="title">イベントページ</span>
            <p><%= link_to @event.event_url, @event.event_url %><br>
            </p>
          </li>
          <li class="collection-item avatar">
            <i class="material-icons circle purple accent-4">search</i>
            <span class="title">イベントid</span>
            <p><%= @event.event_id %><br>
            </p>
          </li>
          <li class="collection-item avatar">
            <i class="material-icons circle purple accent-4">date_range</i>
            <span class="title">時間</span>
            <p><%= @event.started_at %> ~ <%= @event.ended_at %><br>
            </p>
          </li>
          <li class="collection-item avatar">
           <i class="material-icons circle purple accent-4">place</i>
           <span class="title">場所</span>
           <p><%= @event.address %><br>
           </p>
         </li>
        </ul>
      </div>

      <div class="col s6">
        <div class="card">
        <div class="card-image">
          <%= image_tag @event.img_url%>
        </div>
        <div class="card-action">
          <%= link_to "Go to the connpass page", @event.event_url, :target=> "_blank" %>
          <%= link_to 'Back', events_path, :class => "waves-effect waves-light btn" %>
        </div>
      </div>
      </div>
  </div>
</div>

Api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Api</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper red accent-3">
        <a href="/" class="brand-logo">ConnpassViewer</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to "Events", events_path %>/li>
          <li><%= link_to "About", about_path %></li>
          <li><a href="collapsible.html">JavaScript</a></li>
        </ul>
      </div>
    </nav>
    <div id="contents">
      <%= yield %>
    </div>
    <footer class="page-footer red accent-3">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
        </footer>
  </body>
</html>

Api/app/views/staticpage/about.html.erb
<main role="main" class="container">
  <div class="jumbotron">
    <h1>About...</h1>
    <div class="row">
      <div class="col s12 m4">
       <div class="card small">
         <div class="card-content">
           <span class="card-title">ConnpassViewer</span>
           <p>勉強会サイトconnpassをより使いやすくするアプリです。場所の確認や、時間など、見やすくなっております。勉強会への参加はconnpass公式サイトをご利用ください。</p>
         </div>
       </div>
     </div>
     <div class="col s12 m4">
      <div class="card small">
        <div class="card-content">
          <span class="card-title">For mobile</span>
          <p>現在、モバイル版アプリを開発中です。Android版からのリリースになるかと思います。</p>
        </div>
      </div>
    </div>
    <div class="col s12 m4">
     <div class="card small">
       <div class="card-content">
         <span class="card-title">myself</span>
         <p>京都大学大学院に在籍している学生です。</p>
       </div>
     </div>
   </div>
   </div>
  </div>
</main>

Api/app/views/staticpage/help.html.erb
<h1>Staticpage#help</h1>
<p>Find me in app/views/staticpage/help.html.erb</p>

Api/app/views/staticpage/index.html.erb
<main role="main" class="container">
  <div class="jumbotron">
    <h1>ConnpassViewer</h1>
    <p class="flow-text">This example is a quick exercise to illustrate how the top-aligned navbar works. As you scroll, this navbar remains in its original position and moves with the rest of the page.</p>
    <%= link_to 'See events', events_path, :class => "waves-effect waves-light btn purple accent-4" %>
  </div>
</main>